spring:
  datasource:
    url: jdbc:mysql://192.167.31.214:3306/springcloudkeith?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
env:
  dev
