server:
  port: 8081
spring:
  application:
    name: keith-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShenItKeith/config-repro.git
          username: it_keith@163.com
          password: 870216032shen
eureka:
  instance:
    hostname: keith-config
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
